Trading agreement fix for Germans
As a German trying to place an order via the API you will get an
exception: 'EOrder:Trading agreement required'.
You have to set the 'trading_agreement' parameter to 'agree' (see
https://support.kraken.com/hc/en-us/articles/360000920026--Trading-agreement-required-error-for-German-residents).